services:
  - type: web
    name: smartlife-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: smartlife-secret-key-change-later
      - key: FRONTEND_URL
        value: "*"
    plan: free
